dist: bionic

language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.cache/composer

env:
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~3.4.0"
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~4.4.0"
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~5.0.0"

matrix:
  include:
    - php: 7.2
      env: PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~3.4.0" DEPS="low"
    - php: 7.4
      env: RUN_PHPSTAN="yes"
    - php: 7.4
      env: RUN_PSALM="yes"
    - env: ~
      php: ~
      cache: ~
      language: node_js
      node_js: node
      install: yarn install
      before_script: ~
      script: yarn run prod
  fast_finish: true

branches:
  only:
    - master
    - /^\d.\d+$/

before_script:
  - phpenv config-rm xdebug.ini || true
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Read-only OAuth token to work around GitHub API rate limits
  - composer config -g github-oauth.github.com "4b3b0a83ea27d9544d3608a384c7a14625a98804"

  # Install Flex as a global dependency to enable usage of extra.symfony.require
  # while keeping Flex recipes from applying
  - composer global require --no-scripts symfony/flex

  - if [ "$SYMFONY_VERSION" != "" ] ; then composer config extra.symfony.require $SYMFONY_VERSION ; fi

  - composer update --no-suggest --prefer-dist

  - |
    if [ "$DEPS" = "low" ] ; then
      composer update --no-suggest --prefer-dist --prefer-lowest --prefer-stable
    fi

script:
  - composer validate --strict
  - if [ "$PHPUNIT_CONFIG" != "" ] ; then vendor/bin/phpunit -c $PHPUNIT_CONFIG --colors=always ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan-tests ; fi
  - if [ "$RUN_PSALM" != "" ] ; then composer psalm ; fi

notifications:
  email: false
  slack:
    rooms:
      - secure: "pLr4TdeKkSFjkZMZE0op8CYn8epBrLfD51i7vRvnAwWM3gA866ST2n8AKqyJIl3roAAtOiN2D10fIQgoJgzGB4j/na4U3cB7VY92EcRhKRcrbrbPtvAslK63FRxh7SjdXHnSMiErK9QCa6oSFYRf5WT9JvJBblLQrc4r1QHlW0Aw5Bx7ydelX7Q3jxW44yKJDNYn9M2/iNpX35QWjlrF/nphVTTbWkAVrrHPMRPK37JVLVCZjn8uugcGI8N7ewg52CSk3igBAwJXa4m0ZZP5exD8jEvooHjPcfbZ1T+gq8JFGFwquDqN7h5d+CuJe9xOxVUdQNyeI1vbFih/gPQS8WSpcW+ORhu719KDHWRGWZwhLjs6DpFIk/1uOcvjP44Xgn4py32ZTwT062UrHEzRavnBxa5a8UMcVtx8+BpvCVSLEA7ZTrL2GFRWDenDoc03kENEZeB5G7JX5IcfwcduaI+6R0U8+mgAIZfl3fOGbqZgxt29eifjWueqWqtJbcoArd/CFbeyWvE/c+FugViLmHWlV3jiphzua3GYLcSJ3RvQlH/1H1Dwq0ehMkK5IyKvnotEl08HlKm+9VcKy/WNtod4A0AOB19O0issVEoYkBZjmKGq0AgRIkh56Ow/HjejxwG4r/lylJS1IlBtaS/LCwWwPwPnWGBf2a05IOJg8Dg="
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 1
