block_definitions:
    title:
        name: 'Title'
        translatable: true
        view_types:
            title:
                name: 'Title'

    text:
        name: 'Text'
        translatable: true
        view_types:
            text:
                name: 'Text'

    button:
        name: 'Button / Link'
        translatable: true
        view_types:
            button:
                name: 'Button / Link'

    markdown:
        name: 'Markdown'
        enabled: false
        translatable: true
        view_types:
            markdown:
                name: 'Markdown'

    rich_text:
        name: 'Rich text'
        translatable: true
        view_types:
            rich_text:
                name: 'Rich text'

    html_snippet:
        name: 'HTML snippet'
        view_types:
            html_snippet:
                name: 'HTML snippet'

    full_view:
        name: 'Full view'
        view_types:
            full_view:
                name: 'Full view'

    twig_block:
        name: 'Twig block'
        view_types:
            twig_block:
                name: 'Twig block'

    external_video:
        name: 'External video'
        view_types:
            external_video:
                name: 'External video'

    map:
        name: 'Map'
        forms:
            full:
                enabled: false
            content: ~
            design: ~
        view_types:
            map:
                name: 'Map'

    list:
        name: 'List'
        collections: ~
        forms:
            full:
                enabled: false
            content: ~
            design: ~
        view_types:
            list:
                name: 'List'
                valid_parameters: ['!number_of_columns']
            grid:
                name: 'Grid'

    gallery:
        name: 'Gallery'
        collections: ~
        forms:
            full:
                enabled: false
            content: ~
            design: ~
        view_types:
            slider:
                name: 'Slider'
                valid_parameters:
                    - '!pagination_type'
                    - '!autoplay_time'
                    - '!number_of_thumbnails'
                    - '!show_details'
                    - '!show_details_on_hover'
                    - '!enable_lightbox'
            thumb_gallery:
                name: 'Thumb gallery'
                valid_parameters:
                     - '!show_pagination'
                     - '!pagination_type'
                     - '!infinite_loop'
                     - '!transition'
                     - '!autoplay'
                     - '!autoplay_time'
                     - '!number_of_thumbnails'
                     - '!show_details_on_hover'
                     - '!enable_lightbox'
            grid_gallery:
                name: 'Grid gallery'
                valid_parameters:
                     - '!next_and_previous'
                     - '!show_pagination'
                     - '!pagination_type'
                     - '!infinite_loop'
                     - '!transition'
                     - '!autoplay'
                     - '!autoplay_time'
                     - '!show_details'
                     - '!show_details_on_hover'
            sushi_bar:
                name: 'Sushi bar'
                valid_parameters:
                     - '!pagination_type'
                     - '!transition'
                     - '!autoplay_time'
                     - '!show_details'
                     - '!show_details_on_hover'
                     - '!enable_lightbox'

    column:
        name: 'Column'
        translatable: true
        view_types:
            column:
                name: 'Column'

    two_columns:
        name: 'Two columns'
        translatable: true
        view_types:
            two_columns_50_50:
                name: '50:50'
            two_columns_33_66:
                name: '33:66'
            two_columns_66_33:
                name: '66:33'
